# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cc91820cec1b3764ac2263aed6667408"
name = "wc-rahul-testing"
handle = "wc-rahul-testing"
application_url = "https://impression-recipients-furnished-donated.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://impression-recipients-furnished-donated.trycloudflare.com/auth/callback",
  "https://impression-recipients-furnished-donated.trycloudflare.com/auth/shopify/callback",
  "https://impression-recipients-furnished-donated.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
